services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PSB\PsbFoundation\:
    resource: '../Classes/*'

  PSB\PsbFoundation\Service\Configuration\TcaService:
    public: true

  PSB\PsbFoundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true
