services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PSB\PsbFoundation\:
    resource: '../Classes/*'

  PSB\PsbFoundation\EventListener\AfterPackageActivationEventListener:
    tags:
      - event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
        identifier: 'registerExtensionInformation'
        name: event.listener

  PSB\PsbFoundation\EventListener\AfterPackageDeactivationEventListener:
    tags:
      - event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent
        identifier: 'deregisterExtensionInformation'
        name: event.listener

  PSB\PsbFoundation\Service\Configuration\TcaService:
    public: true

  PSB\PsbFoundation\Service\ExtensionInformationService:
    public: true

  PSB\PsbFoundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true

  PSB\PsbFoundation\Service\TypoScriptProviderService:
    public: true
